// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMFDJTvMVQQwUT8h6lWyp-ai9-WMEdKio',
    appId: '1:161855409927:web:6d5ad55272bdb3e77affa2',
    messagingSenderId: '161855409927',
    projectId: 'login-78e34',
    authDomain: 'login-78e34.firebaseapp.com',
    storageBucket: 'login-78e34.appspot.com',
    measurementId: 'G-GYQSCZDVQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXVBgT26MWNNZSh8TdaTpHoVcjM3TD0yQ',
    appId: '1:161855409927:android:f7c308540eaa3caa7affa2',
    messagingSenderId: '161855409927',
    projectId: 'login-78e34',
    storageBucket: 'login-78e34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABtWDNZ-Bx_MKaiLwnd6znNWRsHNKk9U8',
    appId: '1:161855409927:ios:44536d69421821667affa2',
    messagingSenderId: '161855409927',
    projectId: 'login-78e34',
    storageBucket: 'login-78e34.appspot.com',
    iosClientId: '161855409927-l4n6boc5l38jcncdnomhn474k603aqjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );

}
